export const LOCATION = 'LOCATION';
export const LOADING = 'LOADING';
export const DATE_CHANGE_SUCCESS = 'DATE_CHANGE_SUCCESS';
export const DATE_CHANGE_ERROR = 'DATE_CHANGE_ERROR';
export const CANDIDATE_DETAILS = 'CANDIDATE_DETAILS';
export const SELECTED_ITEM = 'SELECTED_ITEM';
