export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const STORE_QUERY = 'STORE_QUERY';
export const SURCHARGE_UPDATED = 'SURCHARGE_UPDATED';

export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS';
export const CREATE_TOKEN_ERROR = 'CREATE_TOKEN_ERROR';
