export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const STORE_QUERY = 'STORE_QUERY';
export const SURCHARGE_UPDATED = 'SURCHARGE_UPDATED';

export const CARD_NUMBER_UPDATED = 'CARD_NUMBER_UPDATED';
export const EXPIRY_UPDATED = 'EXPIRY_UPDATED';
export const CVV_UPDATED = 'CVV_UPDATED';

export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
