export default {
    ajaxCallsInProgress: 0,
    payment: {
        paymentApiActive: true,
        paymentSuccess: false,
        paymentError: false,
        surcharge: 0,
        cardType: '',
        complete: false,
        amount: null,
        customerNumber: null,
        invoiceNumber: null,
        cvv: null,
        cardNumber: null,
        expiry: null,
        formTouched: false,
        toggle: false,
        cardNumberValid: true,
        expiryValid: true,
        cvvValid: true,
    },
};
