export default {
    ajaxCallsInProgress: 0,
    payment: {
        paymentApiActive: true,
        paymentSuccess: true,
        paymentError: false,
        paymentErrorMessage: '',
        surcharge: 0,
        cardType: '',
        complete: false,
        amount: null,
        totalAmount: null,
        customerNumber: null,
        invoiceNumber: null,
        cvv: null,
        cardNumber: null,
        expiry: null,
        toggle: false,
        cardNumberValid: false,
        cardNumberTouched: false,
        expiryValid: false,
        expiryTouched: false,
        cvvValid: false,
        cvvTouched: false,
    },
};
